{% set name = "faicons" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/faicons-{{ version }}.tar.gz
  sha256: 6b7d7b19180179b6b83783f91bf6c9311c0f00ae0f97d41be1d24d9942361659

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - htmltools >=0.1.4.9002

test:
  imports:
    - faicons
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rstudio/py-faicons
  summary: An interface to Font-Awesome for use in Shiny.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
